// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgkEkcyhq2swIgSfaoHSpf0vAxgl5Xhao',
    appId: '1:1027220963414:web:3111bc0fb093b1a18f7bf7',
    messagingSenderId: '1027220963414',
    projectId: 'beltei',
    authDomain: 'beltei.firebaseapp.com',
    storageBucket: 'beltei.appspot.com',
    measurementId: 'G-RYBCST8RX6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7zBVe3DmhLcoaTbK0y58wiGXw4LgZuWM',
    appId: '1:1027220963414:android:6480de35b95ca4508f7bf7',
    messagingSenderId: '1027220963414',
    projectId: 'beltei',
    storageBucket: 'beltei.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5tftCQAFSXhNGvlhoq4sAKeyWfXl_L24',
    appId: '1:1027220963414:ios:8b2d2ac2f8ffdf458f7bf7',
    messagingSenderId: '1027220963414',
    projectId: 'beltei',
    storageBucket: 'beltei.appspot.com',
    iosBundleId: 'kh.edu.beltei.mad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5tftCQAFSXhNGvlhoq4sAKeyWfXl_L24',
    appId: '1:1027220963414:ios:66a3c6097d626a508f7bf7',
    messagingSenderId: '1027220963414',
    projectId: 'beltei',
    storageBucket: 'beltei.appspot.com',
    iosBundleId: 'com.example.mad3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgkEkcyhq2swIgSfaoHSpf0vAxgl5Xhao',
    appId: '1:1027220963414:web:71dbd3fd00029c198f7bf7',
    messagingSenderId: '1027220963414',
    projectId: 'beltei',
    authDomain: 'beltei.firebaseapp.com',
    storageBucket: 'beltei.appspot.com',
    measurementId: 'G-R3QBR91RC7',
  );
}
